import SwiftUI
import UIKit
import PDFKit

struct SitterPlant: Identifiable {
    let id: String
    let nickname: String
    let species: String
    let waterText: String
    let nextWateringText: String
    let lightText: String
    let humidityText: String
    let toxicityText: String
    let locationInHome: String?
    let notes: String?
    let bloomText: String?
}

struct SitterCardView: View {
    let owner: String
    let ownerContact: String
    let plant: SitterPlant

    var body: some View {
        VStack(alignment: .leading, spacing: 18) {
            VStack(alignment: .leading, spacing: 4) {
                Text("Plant Sitter Care Card").font(.title2.weight(.bold))
                Text(owner.isEmpty ? "Your friend's jungle" : "From \(owner)")
                    .font(.subheadline).foregroundStyle(.secondary)
                if !ownerContact.isEmpty {
                    Text("Contact: \(ownerContact)").font(.caption)
                }
            }

            Divider()

            VStack(alignment: .leading, spacing: 4) {
                Text(plant.nickname).font(.title3.weight(.semibold))
                Text(plant.species).font(.caption).italic().foregroundStyle(.secondary)
                if let loc = plant.locationInHome, !loc.isEmpty {
                    Text("Location: \(loc)").font(.caption)
                }
            }

            row(icon: "drop.fill", title: "Water", body: plant.waterText)
            row(icon: "calendar", title: "Next watering", body: plant.nextWateringText)
            row(icon: "sun.max.fill", title: "Light", body: plant.lightText)
            row(icon: "humidity.fill", title: "Humidity", body: plant.humidityText)
            row(icon: "exclamationmark.shield", title: "Toxicity", body: plant.toxicityText)
            if let bloom = plant.bloomText {
                row(icon: "leaf.fill", title: "Blooming", body: bloom)
            }
            if let notes = plant.notes, !notes.isEmpty {
                row(icon: "note.text", title: "Owner notes", body: notes)
            }

            Spacer(minLength: 0)
            Text("Generated by HousePlants.ai")
                .font(.caption2).foregroundStyle(.tertiary)
        }
        .padding(36)
        .frame(width: 612, height: 792, alignment: .topLeading) // US Letter @ 72dpi
        .background(Color.white)
    }

    private func row(icon: String, title: String, body: String) -> some View {
        HStack(alignment: .top, spacing: 10) {
            Image(systemName: icon).foregroundStyle(.green).frame(width: 22)
            VStack(alignment: .leading, spacing: 2) {
                Text(title).font(.caption.weight(.semibold)).foregroundStyle(.secondary)
                Text(body).font(.body)
            }
        }
    }
}

enum SitterCardRenderer {
    @MainActor
    static func renderPDF(owner: String, ownerContact: String, plants: [SitterPlant]) -> URL? {
        guard !plants.isEmpty else { return nil }

        let url = FileManager.default.temporaryDirectory
            .appendingPathComponent("plant-sitter-\(Int(Date().timeIntervalSince1970)).pdf")

        let pageRect = CGRect(x: 0, y: 0, width: 612, height: 792)
        let renderer = UIGraphicsPDFRenderer(bounds: pageRect)

        do {
            try renderer.writePDF(to: url) { ctx in
                for plant in plants {
                    ctx.beginPage()
                    let card = SitterCardView(owner: owner, ownerContact: ownerContact, plant: plant)
                    let r = ImageRenderer(content: card)
                    r.scale = 2.0
                    if let img = r.uiImage {
                        img.draw(in: pageRect)
                    }
                }
            }
        } catch {
            print("Sitter PDF render error: \(error)")
            return nil
        }

        return url
    }
}
